### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by zenabo1** [bpaquet/ngx_http_enhanced_memcached_module#14]
This module works without using  PUT request, so what i mean is if memcahed dont have the key, later the module store the key auttomatically, and for future requests memcached can serve?
code

events{worker_connections 1024; }
 http {
              server {

                location / {

                        set $enhanced_memcached_key "$request_uri";
                        enhanced_memcached_allow_put on;
                        enhanced_memcached_pass localhost:11211;
                     error_page        404  = @dynamic_request;
                }

                location  @dynamic_request  {
                       proxy_pass  http://193.136.9.15:80;
                }
        }
}

**Comment by bpaquet** [comment]
No the module does not store data automatically. May be your memcached already contains some data.
