### ISSUE TITLE
flush by path prefix how can i do this

### ISSUE THREAD

**Issue by vtolstov** [bpaquet/ngx_http_enhanced_memcached_module#17]
i'm try to use this module but i need to flush cache by path prefix, for example if user post to any files on zzz/zzz zzz/aaa zzz/ttt i need to flush cache for any keys that in zzz/

**Comment by bpaquet** [comment]
Memcached has no command to list keys, so you cannot do that.
In most of cases, key namespaces can be used as workaround (changing the
key of a namespaces is equivalent to a flush of this namespaces). See doc.

**Comment by vtolstov** [comment]
thanks. namespace can fix my issue.
